### ISSUE TITLE
monolithic file should be exploded into fragments

### ISSUE THREAD

**Issue by pelevesque** [Trung0246/Funch#2]
It would be a good idea to explode this monolithic file into one file per function. 

This would make testing, exporting, and maintenance much easier.

**Comment by Trung0246** [comment]
> One file per function

How about one file for each member? (Ex: math.js, geometry.js,...)? Does it makes any difference?

**Comment by pelevesque** [comment]
Sure. What would be cool is to have the collection as a node module with tree shaking possibilities. 

You could then do:

```
const funch = require('funch') // loads entire library
const funchMath = require('funch').math // only loads math functions
const funchMathLog = require('funch').math.log // only load the log function
```

**Comment by Trung0246** [comment]
Thx for the idea... But I'm not sure about this:

I was thinking about adding a way to dynamically changing export function (located at bottom of the file) to user-defined export function upon loading the library. This would mean that users can easily change the way functions being exported to fit with their needs (Ex: creating a function export to "Funch" object and using module.exports to export that "Funch" object (the way you suggested) and replacing default way (exporting functions to global objects) dynamically)

Any other ideas?

**Comment by pelevesque** [comment]
simple is best
